KTB-14 update id and text parsed
JohnnyGomezzz/KotlinTelegramBot pull request #11
Opened 2024-11-26 15:32 UTC by JohnnyGomezzz

2024-11-27 19:48 UTC, dzenonce requested changes

2024-11-27 19:48 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val updateIdRegex: Regex = "\"update_id\":(\\d+),".toRegex()
Regex лучше записать в переменную за пределами while. Мы стараемся не пересоздавать переменные лишний раз.

2024-11-27 19:48 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        updateId = idGroups[1]?.value?.toInt()!! + 1
А давай делать continue если updateId null, а вот использование `!!` это довольно плохая практика, можно поймать NPE и порой не сразу понятно в чем проблема

2024-11-28 08:08 UTC, dzenonce approved these changes
Все огонь, идем дальше

2024-11-28 08:08 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        updateId = updateIdGroups?.get(1)?.value?.toInt()?.plus(1)
Лучше делать вот так, будет еще короче запись
`.toIntOrNull()?.plus(1) ?: continue`

2024-11-28 08:08 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        if (updateId == null) continue
А это уберем

2024-11-28 08:14 UTC, JohnnyGomezzz commented on src/main/kotlin/Telegram.kt
> +        updateId = updateIdGroups?.get(1)?.value?.toInt()?.plus(1)
Точно, спасибо)

2024-11-28 08:14 UTC, merged